### ISSUE TITLE
Should this also be in the Journey Optimizer documentation?

### ISSUE THREAD

**Issue by nhecht** [AdobeDocs/journeys.en#5]
Issue in ./help/using/datasource/external-data-sources.md

I could not find this documentation in Journey Optimizer, but Journey Optimizer also has this functionality. 
Trying to understand what docs are under Journey Orchestration vs. Journey Optimizer. When the functionality exists in both.

**Comment by Alicesnk** [comment]
The page is available here > https://experienceleague.adobe.com/docs/journey-optimizer/using/configuration/configure-journeys/data-source-journeys/external-data-sources.html?lang=en
