### ISSUE TITLE
Function names missing against the categories

### ISSUE THREAD

**Issue by happyahluwalia** [AdobeDocs/journeys.en#6]
Issue in ./help/using/expression/functions.md
<img width="894" alt="image" src="https://user-images.githubusercontent.com/8081182/88485051-f9369700-cf27-11ea-8978-5cd8ac285c27.png">

Against the categories the function name should be shown. The functions are missing.
https://experienceleague.adobe.com/docs/journeys/using/building-advanced-conditions-journeys/main-functions-journey/functions.html?lang=en#concept_p1r_qj5_dgb

**Comment by floflo492** [comment]
Hi, thanks for your feedback. Here is the correct page for Journey Orchestration documentation:
https://docs.adobe.com/content/help/en/journeys/using/building-advanced-conditions-journeys/main-functions-journey/functions.html
Florent

**Comment by FlorentVAdobe** [comment]
Hi @happyahluwalia can you please close the issue?
Thanks,
Florent
